// Web/UI/Routes/ACMEs/ACME/index.tsx
import React from 'react';
import { useParams } from 'react-router';
import { useAcmeQuery } from './ACME.gen';
import { Header } from 'UI/Components/Styles/Header';
import { PageSectionRoot } from 'UI/Components/Styles/Section/PageSectionRoot';
import { PaperSection } from 'UI/Components/Styles/Section/PaperSection';
import { BaseButton } from 'UI/Components/Styles/Button/BaseButton';
import { useStyles } from 'UI/Components/Styles';
import { ACMEDomainsPanel } from './ACMEDomainsPanel';
import { Typography } from '@material-ui/core';
import { BaseList } from 'UI/Components/Styles/List/BaseList';
import { LabelListItem } from 'UI/Components/Styles/List/ListItems/LabelListItem';

interface ACMEPageParams {
  acmeId: string;
}

export default function ACMEPage(): React.ReactElement {
  const classes = useStyles();
  const { acmeId } = useParams<ACMEPageParams>();
  const { data } = useAcmeQuery({
    variables: {
      acmeId,
    },
  });

  console.log(data);

  return (
    <>
      <Header title={{ primary: `${data?.ACME.name} ACME` }} />
      <div className={classes.pageRoot}>
        <PageSectionRoot>
          <ACMEDomainsPanel acmeData={data} />

          <PaperSection>
            <Typography variant='body1'>
              Certificates generated by Distributed DNS & Let's encrypt
            </Typography>
            <BaseList>
              {(data?.ACME.certificates || []).map(({ id, createdAt }) => (
                <LabelListItem key={id} label={{ primary: createdAt }} />
              ))}
            </BaseList>

            <BaseButton
              label='Generate Certificate'
              onClick={() => console.log('Saving Settings')}
              color='primary'
              variant='contained'
            />
          </PaperSection>
        </PageSectionRoot>
      </div>
    </>
  );
}
